### ISSUE TITLE
Listing regions errors with "requires authentication"

### ISSUE THREAD

**Issue by koslib** [planetscale/planetscale-go#152]
Hello,

I got a service token created which has been validated as working with other API operations.

Trying to list regions:

```
regions, err := d.client.Regions.List(ctx, &planetscale.ListRegionsRequest{})
	if err != nil {
		fmt.Print(err.Error())
		return
	}
```

however this fails with 

```
Requires authentication
```

I've enabled all permissions across the db and org for my service token but still returns this error. Am I doing something wrong probably or is this an actual issue with the sdk/API? 

Update: I might need to go through the `d.client.Organizations.ListRegions` func instead, but then I don't get the difference between the two?

**Comment by mscoutermarsh** [comment]
Sorry for the delay in responding to this. Yes, you'll want to use `d.client.Organizations.ListRegions`.

**Context:**
Service tokens are scoped to an organization. We have a small number of endpoints that are outside of the organization scope (such as `d.client.Regions.List`).

The difference between these endpoints is that `d.client.Regions.List` returns all regions we have available (to the currently logged in user). `d.client.Organizations.ListRegions` returns all regions available to an organization.

These two lists are in most cases identical. But for some organizations (such as those who use [PlanetScale Managed](https://planetscale.com/docs/concepts/deployment-options#single-tenancy-deployment-on-planetscale)), they have a different list of available regions.
