### ISSUE TITLE
Connecting to a DB docs outdated

### ISSUE THREAD

**Issue by sourdoughdev** [planetscale/planetscale-go#88]
👋 I've noticed that `dbutil` was dropped via #84, leaving the [doc example broken](https://github.com/planetscale/planetscale-go/tree/9d0969b22140df09fe5089ab0e1a946fc9dad628#connecting-to-a-planetscale-database).

I was hoping there was an alternative way to connect instead of running `pscale`.

**Comment by sourdoughdev** [comment]
[Connection strings](https://docs.planetscale.com/concepts/connection-strings) look like a good way to solve this.

**Comment by fatih** [comment]
@sourdoughdev thanks for the feedback. I opened PR that removes it from the readme: https://github.com/planetscale/planetscale-go/pull/91
